################################
# Slack connection settings
################################
token: "YOUR-TOKEN-HERE" # API authentication token
subdomain: some-domain # Part of domain before .campfire.com
use_ssl: yes # Use SSL to communicate with Campfire? yes or no
log_file: /var/log/giantdwarf.log
log_mode: normal # Log mode can either be debug or normal

###########################################################
# Passive plugins are those that do stuff in the background
# and update Campfire when external events happen. Nagios
# is a good example of a passive plugin
###########################################################
plugins:
    # Module and class name to be called within module
    # in the following format
    #
    # ClassName: module.location
    #
    # Eg: Nagios: GiantDwarf.plugins.nagios
    nagios: plugins.nagios

# ########################################################
# Plugin specific settings
# ########################################################
nagios:
    room: 'nagios'
    instances:
        - {'name': 'Prod', 'url': 'https://somewhere.com/nagios/', 'username': 'my-username', 'password': 'my-password'}
